name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deploy-azure
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deploy-azure

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Instalar dependencias
        run: |
          cd WebChat
          npm install

      - name: Ejecutar Build
        run: |
          cd WebChat
          npm run build

      - name: Verificar archivos generados
        run: |
          ls -la WebChat/dist

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_PEBBLE_00AE4940F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integraciones con GitHub (PRs, etc.)
          action: "upload"
          ###### Configuración del repositorio y build ######
          app_location: "WebChat" # Carpeta donde está el código fuente
          api_location: "" # No se usa API en este proyecto
          output_location: "dist" # Carpeta donde se genera el build
          ###### Fin de configuración ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_PEBBLE_00AE4940F }}
          action: "close"
